import logfire
from dotenv import load_dotenv

from pydantic_ai import Agent, ModelMessage, ModelRequest

from datastructures.TripDescriptor import TripDescriptor
from datastructures.CustomerDescriptor import CustomerDescriptor
from datastructures.Recommendation import Recommendation
from datastructures.MyDeps import MyDeps
from datastructures.agents_response import Itinerary, GPXDataIsReady, MessageToCustomer

load_dotenv()

logfire.configure(send_to_logfire="if-token-present")
logfire.instrument_pydantic_ai()
logfire.instrument_requests()
Agent.instrument_all()

from crew.route_planner_agent import route_planner
from crew.route_calculator_agent import route_calculator



def run_route_planner() -> Itinerary | None:
    history: list[ModelMessage] = []
    user_input = ""

    while True:
        result = route_planner.run_sync(user_input, message_history=history)

        if isinstance(result.output, Itinerary):
            return result.output

        # Add to the history the newer messages
        # The ones generated by the last run of the Agent
        history.extend(result.new_messages())

        # Present the Agent response to the user
        print("Agent: ", result.output, sep="\n")

        # Get the input from the user
        # Actually the User response to the Agent response
        user_input = input("User:\n")
        if user_input.lower().strip() in ("exit", "quit"):
            print("The user forced loop termination")
            return None


def run_route_calculator(deps: MyDeps) -> GPXDataIsReady | None:
    history: list[ModelMessage] = []
    user_input = ""

    while True:
        result = route_calculator.run_sync(user_input, message_history=history, deps=deps)

        if isinstance(result.output, MessageToCustomer):
            # Add to the history the newer messages
            # The ones generated by the last run of the Agent
            history.extend(result.new_messages())

            # Present the Agent response to the user
            print("Agent: ", result.output.message, sep="\n")

            # Get the input from the user
            # Actually the User response to the Agent response
            user_input = input("User:\n")
            if user_input.lower().strip() in ("exit", "quit"):
                print("The user forced loop termination")
                return None

        elif isinstance(result.output, GPXDataIsReady):
            return result.output


        
if __name__ == "__main__":
    planner_result: Itinerary | None = run_route_planner()
    # For testing purposes (bypass the planner)
    # planner_result = Itinerary(stages=['Cividale del Friuli, Italy', 'Stregna, Italy', 'Pulfero, Italy', 'San Daniele del Friuli, Italy', 'Tarvisio, Italy'])
    # planner_result = Itinerary(stages=['Padova, Italy', 'Vittorio Veneto, Italy', 'Aviano, Italy', 'Polcenigo, Italy', "Cansiglio, Italy"])
    print(planner_result)

    if planner_result is not None:
        trip = TripDescriptor()
        trip.fill(itinerary=planner_result.stages)

        deps = MyDeps(
            trip=trip,
            user=CustomerDescriptor(),
        )
        calculator_result: GPXDataIsReady | None = run_route_calculator(deps)

        print(calculator_result)

        print("\n")

        gpx_data = deps.trip.get_gpx_route()
        if gpx_data is not None:
            with open("output_route.gpx", "w") as f:
                f.write(gpx_data)
    else:
        logfire.log("info", "No itinerary generated, skipping route calculation")
