import logfire
from dotenv import load_dotenv

from pydantic_ai import Agent, ModelMessage, ModelRequest

from datastructures.TripDescriptor import TripDescriptor
from datastructures.UserDescriptor import UserDescriptor
from datastructures.Recommendation import Recommendation
from datastructures.MyDeps import MyDeps
from datastructures.FinalResults import PlannerFinalResult

load_dotenv()

logfire.configure(send_to_logfire="if-token-present")
logfire.instrument_pydantic_ai()
logfire.instrument_requests()
Agent.instrument_all()

from crew.route_planner_agent import route_planner
from crew.route_calculator_agent import route_calculator



def run_route_planner():
    history: list[ModelMessage] = []
    user_input = ""

    while True:
        result = route_planner.run_sync(user_input, message_history=history)

        if isinstance(result.output, PlannerFinalResult):
            return result.output
        elif user_input.lower().strip() in ("exit", "quit"):
            print("The user forced loop termination")
            return None

        # Add to the history the newer messages
        # The ones generated by the last run of the Agent
        history.extend(result.new_messages())

        # Present the Agent response to the user
        print("Agent: ", result.output, sep="\n")

        # Get the input from the user
        # Actually the User response to the Agent response
        user_input = input("User:\n")


        
if __name__ == "__main__":
    result = run_route_planner()
    print(result)
